[package]
name = "ogg-sys"
version = "0.0.3"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
build = "libogg/build.rs"
links = "ogg"
description = "FFI for libogg, the media container."
license = "MIT"
repository = "https://github.com/tomaka/ogg-sys"

[build-dependencies]
gcc = "*"
pkg-config = "*"
